CREATE TABLE `supply_chain`.`geo_country` (
  `COUNTRY_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `COUNTRY_NAME` VARCHAR(45) NOT NULL COMMENT '',
  `COUNTRY_CODE` VARCHAR(4) NOT NULL COMMENT '',
  PRIMARY KEY (`COUNTRY_ID`)  COMMENT '',
  UNIQUE INDEX `COUNTRY_CODE_UNIQUE` (`COUNTRY_CODE` ASC)  COMMENT '');

CREATE TABLE `supply_chain`.`geo_state` (
  `STATE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `STATE_NAME` VARCHAR(45) NOT NULL COMMENT '',
  `STATE_CODE` VARCHAR(4) NOT NULL COMMENT '',
  `STATE_COUNTRY` INT NOT NULL COMMENT '',
  PRIMARY KEY (`STATE_ID`)  COMMENT '',
  UNIQUE INDEX `STATE_NAME_UNIQUE` (`STATE_NAME` ASC, `STATE_COUNTRY` ASC)  COMMENT 'state once for country');

ALTER TABLE `supply_chain`.`geo_state` 
ADD INDEX `FK_STATE_idx` (`STATE_COUNTRY` ASC)  COMMENT '';
ALTER TABLE `supply_chain`.`cat_state` 
ADD CONSTRAINT `FK_STATE_COUNTRY`
  FOREIGN KEY (`STATE_COUNTRY`)
  REFERENCES `supply_chain`.`cat_country` (`COUNTRY_ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  CREATE TABLE `supply_chain`.`sys_storage` (
  `STORAGE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `STORAGE_CODE` VARCHAR(4) NOT NULL COMMENT '',
  `STORAGE_NAME` VARCHAR(30) NOT NULL COMMENT '',
  `STORAGE_STREET_ADDRESS` VARCHAR(100) NULL COMMENT '',
  `STORAGE_ADDITIONAL_ADDRESS` VARCHAR(100) NULL COMMENT '',
  `STORAGE_CITY` VARCHAR(50) NULL COMMENT '',
  `STORAGE_STATE` INT NULL COMMENT '',
  `STORAGE_ZIP` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`STORAGE_ID`)  COMMENT '',
  UNIQUE INDEX `STORAGE_CODE_IDX` (`STORAGE_CODE` ASC) COMMENT '',
  UNIQUE INDEX `STORAGE_NAME_IDX` (`STORAGE_NAME` ASC) COMMENT '',
  INDEX `FK_STORAGE_STATE_idx` (`STORAGE_STATE` ASC)  COMMENT '',
  FOREIGN KEY (`STORAGE_STATE`) REFERENCES `supply_chain`.`geo_state` (`STATE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
  );

/**  INSERT ALL COUNTRIES **/
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('1', 'Afghanistan', 'AFG');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('2', 'Albania', 'ALB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('3', 'Algeria', 'DZA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('4', 'American Samoa', 'ASM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('5', 'Andorra', 'AND');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('6', 'Angola', 'AGO');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('7', 'Anguilla', 'AIA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('8', 'Antarctica', 'ATA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('9', 'Antigua and Barbuda', 'ATG');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('10', 'Argentina', 'ARG');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('11', 'Armenia', 'ARM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('12', 'Aruba', 'ABW');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('13', 'Australia', 'AUS');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('14', 'Austria', 'AUT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('15', 'Azerbaijan', 'AZE');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('16', 'Bahamas', 'BHS');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('17', 'Bahrain', 'BHR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('18', 'Bangladesh', 'BGD');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('19', 'Barbados', 'BRB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('20', 'Belarus', 'BLR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('21', 'Belgium', 'BEL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('22', 'Belize', 'BLZ');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('23', 'Benin', 'BEN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('24', 'Bermuda', 'BMU');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('25', 'Bhutan', 'BTN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('26', 'Bolivia', 'BOL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('27', 'Bonaire', 'BES');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('28', 'Bosnia and Herzegovina', 'BIH');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('29', 'Botswana', 'BWA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('30', 'Bouvet Island', 'BVT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('31', 'Brazil', 'BRA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('32', 'British Indian Ocean Territory', 'IOT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('33', 'Brunei Darussalam', 'BRN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('34', 'Bulgaria', 'BGR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('35', 'Burkina Faso', 'BFA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('36', 'Burundi', 'BDI');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('37', 'Cambodia', 'KHM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('38', 'Cameroon', 'CMR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('39', 'Canada', 'CAN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('40', 'Cape Verde', 'CPV');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('41', 'Cayman Islands', 'CYM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('42', 'Central African Republic', 'CAF');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('43', 'Chad', 'TCD');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('44', 'Chile', 'CHL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('45', 'China', 'CHN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('46', 'Christmas Island', 'CXR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('47', 'Cocos (Keeling) Islands', 'CCK');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('48', 'Colombia', 'COL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('49', 'Comoros', 'COM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('50', 'Congo', 'COG');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('51', 'Democratic Republic of the Congo', 'COD');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('52', 'Cook Islands', 'COK');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('53', 'Costa Rica', 'CRI');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('54', 'Croatia', 'HRV');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('55', 'Cuba', 'CUB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('56', 'CuraÃ§ao', 'CUW');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('57', 'Cyprus', 'CYP');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('58', 'Czech Republic', 'CZE');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('59', 'CÃ´te d\'Ivoire', 'CIV');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('60', 'Denmark', 'DNK');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('61', 'Djibouti', 'DJI');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('62', 'Dominica', 'DMA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('63', 'Dominican Republic', 'DOM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('64', 'Ecuador', 'ECU');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('65', 'Egypt', 'EGY');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('66', 'El Salvador', 'SLV');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('67', 'Equatorial Guinea', 'GNQ');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('68', 'Eritrea', 'ERI');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('69', 'Estonia', 'EST');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('70', 'Ethiopia', 'ETH');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('71', 'Falkland Islands (Malvinas)', 'FLK');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('72', 'Faroe Islands', 'FRO');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('73', 'Fiji', 'FJI');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('74', 'Finland', 'FIN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('75', 'France', 'FRA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('76', 'French Guiana', 'GUF');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('77', 'French Polynesia', 'PYF');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('78', 'French Southern Territories', 'ATF');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('79', 'Gabon', 'GAB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('80', 'Gambia', 'GMB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('81', 'Georgia', 'GEO');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('82', 'Germany', 'DEU');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('83', 'Ghana', 'GHA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('84', 'Gibraltar', 'GIB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('85', 'Greece', 'GRC');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('86', 'Greenland', 'GRL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('87', 'Grenada', 'GRD');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('88', 'Guadeloupe', 'GLP');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('89', 'Guam', 'GUM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('90', 'Guatemala', 'GTM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('91', 'Guernsey', 'GGY');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('92', 'Guinea', 'GIN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('93', 'Guinea-Bissau', 'GNB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('94', 'Guyana', 'GUY');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('95', 'Haiti', 'HTI');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('96', 'Heard Island and McDonald Mcdonald Islands', 'HMD');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('97', 'Holy See (Vatican City State)', 'VAT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('98', 'Honduras', 'HND');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('99', 'Hong Kong', 'HKG');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('100', 'Hungary', 'HUN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('101', 'Iceland', 'ISL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('102', 'India', 'IND');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('103', 'Indonesia', 'IDN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('104', 'Iran, Islamic Republic of', 'IRN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('105', 'Iraq', 'IRQ');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('106', 'Ireland', 'IRL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('107', 'Isle of Man', 'IMN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('108', 'Israel', 'ISR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('109', 'Italy', 'ITA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('110', 'Jamaica', 'JAM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('111', 'Japan', 'JPN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('112', 'Jersey', 'JEY');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('113', 'Jordan', 'JOR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('114', 'Kazakhstan', 'KAZ');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('115', 'Kenya', 'KEN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('116', 'Kiribati', 'KIR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('117', 'Korea, Democratic People\'s Republic of', 'PRK');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('118', 'Korea, Republic of', 'KOR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('119', 'Kuwait', 'KWT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('120', 'Kyrgyzstan', 'KGZ');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('121', 'Lao People\'s Democratic Republic', 'LAO');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('122', 'Latvia', 'LVA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('123', 'Lebanon', 'LBN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('124', 'Lesotho', 'LSO');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('125', 'Liberia', 'LBR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('126', 'Libya', 'LBY');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('127', 'Liechtenstein', 'LIE');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('128', 'Lithuania', 'LTU');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('129', 'Luxembourg', 'LUX');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('130', 'Macao', 'MAC');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('131', 'Macedonia, the Former Yugoslav Republic of', 'MKD');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('132', 'Madagascar', 'MDG');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('133', 'Malawi', 'MWI');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('134', 'Malaysia', 'MYS');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('135', 'Maldives', 'MDV');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('136', 'Mali', 'MLI');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('137', 'Malta', 'MLT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('138', 'Marshall Islands', 'MHL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('139', 'Martinique', 'MTQ');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('140', 'Mauritania', 'MRT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('141', 'Mauritius', 'MUS');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('142', 'Mayotte', 'MYT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('143', 'Mexico', 'MEX');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('144', 'Micronesia, Federated States of', 'FSM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('145', 'Moldova, Republic of', 'MDA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('146', 'Monaco', 'MCO');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('147', 'Mongolia', 'MNG');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('148', 'Montenegro', 'MNE');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('149', 'Montserrat', 'MSR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('150', 'Morocco', 'MAR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('151', 'Mozambique', 'MOZ');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('152', 'Myanmar', 'MMR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('153', 'Namibia', 'NAM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('154', 'Nauru', 'NRU');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('155', 'Nepal', 'NPL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('156', 'Netherlands', 'NLD');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('157', 'New Caledonia', 'NCL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('158', 'New Zealand', 'NZL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('159', 'Nicaragua', 'NIC');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('160', 'Niger', 'NER');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('161', 'Nigeria', 'NGA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('162', 'Niue', 'NIU');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('163', 'Norfolk Island', 'NFK');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('164', 'Northern Mariana Islands', 'MNP');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('165', 'Norway', 'NOR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('166', 'Oman', 'OMN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('167', 'Pakistan', 'PAK');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('168', 'Palau', 'PLW');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('169', 'Palestine, State of', 'PSE');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('170', 'Panama', 'PAN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('171', 'Papua New Guinea', 'PNG');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('172', 'Paraguay', 'PRY');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('173', 'Peru', 'PER');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('174', 'Philippines', 'PHL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('175', 'Pitcairn', 'PCN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('176', 'Poland', 'POL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('177', 'Portugal', 'PRT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('178', 'Puerto Rico', 'PRI');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('179', 'Qatar', 'QAT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('180', 'Romania', 'ROU');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('181', 'Russian Federation', 'RUS');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('182', 'Rwanda', 'RWA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('183', 'Reunion', 'REU');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('184', 'Saint Barthalemy', 'BLM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('185', 'Saint Helena', 'SHN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('186', 'Saint Kitts and Nevis', 'KNA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('187', 'Saint Lucia', 'LCA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('188', 'Saint Martin (French part)', 'MAF');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('189', 'Saint Pierre and Miquelon', 'SPM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('190', 'Saint Vincent and the Grenadines', 'VCT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('191', 'Samoa', 'WSM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('192', 'San Marino', 'SMR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('193', 'Sao Tome and Principe', 'STP');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('194', 'Saudi Arabia', 'SAU');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('195', 'Senegal', 'SEN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('196', 'Serbia', 'SRB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('197', 'Seychelles', 'SYC');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('198', 'Sierra Leone', 'SLE');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('199', 'Singapore', 'SGP');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('200', 'Sint Maarten (Dutch part)', 'SXM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('201', 'Slovakia', 'SVK');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('202', 'Slovenia', 'SVN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('203', 'Solomon Islands', 'SLB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('204', 'Somalia', 'SOM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('205', 'South Africa', 'ZAF');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('206', 'South Georgia and the South Sandwich Islands', 'SGS');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('207', 'South Sudan', 'SSD');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('208', 'Spain', 'ESP');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('209', 'Sri Lanka', 'LKA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('210', 'Sudan', 'SDN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('211', 'Suriname', 'SUR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('212', 'Svalbard and Jan Mayen', 'SJM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('213', 'Swaziland', 'SWZ');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('214', 'Sweden', 'SWE');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('215', 'Switzerland', 'CHE');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('216', 'Syrian Arab Republic', 'SYR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('217', 'Taiwan, Province of China', 'TWN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('218', 'Tajikistan', 'TJK');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('219', 'United Republic of Tanzania', 'TZA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('220', 'Thailand', 'THA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('221', 'Timor-Leste', 'TLS');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('222', 'Togo', 'TGO');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('223', 'Tokelau', 'TKL');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('224', 'Tonga', 'TON');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('225', 'Trinidad and Tobago', 'TTO');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('226', 'Tunisia', 'TUN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('227', 'Turkey', 'TUR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('228', 'Turkmenistan', 'TKM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('229', 'Turks and Caicos Islands', 'TCA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('230', 'Tuvalu', 'TUV');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('231', 'Uganda', 'UGA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('232', 'Ukraine', 'UKR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('233', 'United Arab Emirates', 'ARE');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('234', 'United Kingdom', 'GBR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('235', 'United States', 'USA');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('236', 'United States Minor Outlying Islands', 'UMI');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('237', 'Uruguay', 'URY');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('238', 'Uzbekistan', 'UZB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('239', 'Vanuatu', 'VUT');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('240', 'Venezuela', 'VEN');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('241', 'Viet Nam', 'VNM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('242', 'British Virgin Islands', 'VGB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('243', 'US Virgin Islands', 'VIR');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('244', 'Wallis and Futuna', 'WLF');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('245', 'Western Sahara', 'ESH');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('246', 'Yemen', 'YEM');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('247', 'Zambia', 'ZMB');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('248', 'Zimbabwe', 'ZWE');
INSERT INTO `supply_chain`.`geo_country` (`COUNTRY_ID`, `COUNTRY_NAME`, `COUNTRY_CODE`) VALUES ('249', 'Aland Islands', 'ALA');
/** INSERT ALL STATES **/
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('1', 'Alberta', 'AB', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('2', 'British Columbia', 'BC', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('3', 'Manitoba', 'MB', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('4', 'New Brunswick', 'NB', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('5', 'Newfoundland and Labrador', 'NL', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('6', 'Northwest Territories', 'NT', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('7', 'Nova Scotia', 'NS', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('8', 'Nunavut', 'UN', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('9', 'Ontario', 'ON', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('10', 'Prince Edward Island', 'PE', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('11', 'Quebec', 'QB', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('12', 'Saskatchewan', 'SK', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('13', 'Yukon', 'YK', '39');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('14', 'Aargau', 'AR', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('15', 'Appenzell Ausserrhoden', 'AA', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('16', 'Basel-Country', 'BC', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('17', 'Basle-Ville', 'BV', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('18', 'Bern', 'BE', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('19', 'Fribourg', 'FR', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('20', 'Geneva', 'GE', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('21', 'Glarus', 'GL', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('22', 'Grisons', 'GS', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('23', 'Jura', 'JU', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('24', 'Kanton Appenzell Innerrhoden', 'KAI', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('25', 'Lucerne', 'LU', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('26', 'Neuchâtel', 'NE', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('27', 'Nidwalden', 'NI', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('28', 'Obwalden', 'OB', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('29', 'Saint Gallen', 'SG', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('30', 'Schaffhausen', 'SC', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('31', 'Schwyz', 'SCY', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('32', 'Solothurn', 'SO', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('33', 'Thurgau', 'TH', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('34', 'Ticino', 'TI', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('35', 'Uri', 'UR', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('36', 'Valais', 'VA', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('37', 'Vaud', 'VAU', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('38', 'Zug', 'ZUG', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('39', 'Zurich', 'ZUR', '215');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('40', 'Anhui Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('41', 'Beijing Shi', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('42', 'Chongqing Shi', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('43', 'Fujian', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('44', 'Gansu Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('45', 'Guangdong Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('46', 'Guangxi Zhuangzu Zizhiqu', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('47', 'Guizhou Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('48', 'Hainan', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('49', 'Hebei', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('50', 'Heilongjiang Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('51', 'Henan Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('52', 'Hubei', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('53', 'Hunan', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('54', 'Inner Mongolia', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('55', 'Jiangsu Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('56', 'Jiangxi Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('57', 'Jilin Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('58', 'Liaoning', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('59', 'Ningxia Huizu Zizhiqu', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('60', 'Qinghai Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('61', 'Shaanxi Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('62', 'Shandong Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('63', 'Shanghai Shi', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('64', 'Shanxi Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('65', 'Sichuan Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('66', 'Tianjin Shi', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('67', 'Tibet Autonomous Region', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('68', 'Xinjiang Uygur Zizhiqu', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('69', 'Yunnan', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('70', 'Zhejiang Sheng', 'CHI', '45');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('71', 'Provincia de Alajuela', 'AL', '53');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('72', 'Provincia de Cartago', 'CA', '53');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('73', 'Provincia de Guanacaste', 'GU', '53');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('74', 'Provincia de Heredia', 'HE', '53');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('75', 'Provincia de Limón', 'LI', '53');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('76', 'Provincia de Puntarenas', 'PU', '53');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('77', 'Provincia de San José', 'SJ', '53');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('78', 'Baden-Württemberg', 'BW', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('79', 'Bavaria', 'BA', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('80', 'Brandenburg', 'BR', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('81', 'Bremen', 'BE', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('82', 'Hamburg', 'HA', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('83', 'Hesse', 'HE', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('84', 'Land Berlin', 'LB', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('85', 'Lower Saxony', 'LS', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('86', 'Mecklenburg-Vorpommern', 'MV', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('87', 'North Rhine-Westphalia', 'NR', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('88', 'Rheinland-Pfalz', 'RP', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('89', 'Saarland', 'SL', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('90', 'Saxony', 'SX', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('91', 'Saxony-Anhalt', 'SA', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('92', 'Schleswig-Holstein', 'SH', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('93', 'Thuringia', 'TH', '82');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('94', 'England', 'EN', '234');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('95', 'Guernsey (general)', 'GU', '234');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('96', 'Isle of Man', 'IM', '234');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('97', 'Jersey (general)', 'JE', '234');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('98', 'N Ireland', 'NI', '234');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('99', 'Scotland', 'SC', '234');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('100', 'Wales', 'WL', '234');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('101', 'Bengal', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('102', 'Daman and Diu', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('103', 'Goa', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('104', 'Haryana', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('105', 'Jammu and Kashmir', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('106', 'Kerala', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('107', 'Laccadives', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('108', 'NCT', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('109', 'Rajasthan', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('110', 'State of Andhra Pradesh', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('111', 'State of Arunāchal Pradesh', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('112', 'State of Assam', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('113', 'State of Bihār', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('114', 'State of Chhattīsgarh', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('115', 'State of Gujarāt', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('116', 'State of Himāchal Pradesh', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('117', 'State of Jharkhand', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('118', 'State of Karnātaka', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('119', 'State of Madhya Pradesh', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('120', 'State of Mahārāshtra', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('121', 'State of Manipur', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('122', 'State of Meghālaya', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('123', 'State of Mizoram', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('124', 'State of Nāgāland', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('125', 'State of Odisha', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('126', 'State of Punjab', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('127', 'State of Sikkim', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('128', 'State of Tamil Nādu', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('129', 'State of Tripura', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('130', 'Union Territory of Andaman and Nicobar Islands', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('131', 'Union Territory of Chandīgarh', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('132', 'Union Territory of Dādra and Nagar Haveli', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('133', 'Union Territory of Puducherry', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('134', 'Uttar Pradesh', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('135', 'Uttarakhand', 'IND', '102');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('136', 'Aguascalientes', 'ags.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('137', 'Baja California Sur', 'bcs.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('138', 'Campeche', 'camp.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('139', 'Chiapas', 'chia.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('140', 'Chihuahua', 'chih.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('141', 'Coahuila', 'coah.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('142', 'Colima', 'col.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('143', 'Durango', 'dgo.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('144', 'Estado de Baja California', 'bcn.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('145', 'Estado de México', 'df.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('146', 'Estado de Veracruz-Llave', 'ver.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('147', 'Guanajuato', 'gto.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('148', 'Guerrero', 'gro.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('149', 'Hidalgo', 'hgo.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('150', 'Jalisco', 'jal.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('151', 'Michoacán', 'mich.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('152', 'Morelos', 'mor.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('153', 'Nayarit', 'nyt.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('154', 'Nuevo León', 'nln.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('155', 'Oaxaca', 'oax.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('156', 'Puebla', 'pue.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('157', 'Querétaro', 'qro.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('158', 'Quintana Roo', 'qroo.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('159', 'San Luis Potosí', 'slp.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('160', 'Sinaloa', 'sin.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('161', 'Sonora', 'son.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('162', 'Tabasco', 'tab.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('163', 'Tamaulipas', 'tam.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('164', 'Distrito Federal', 'df.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('165', 'Tlaxcala', 'tlax.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('166', 'Yucatán', 'yuc', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('167', 'Zacatecas', 'zac.', '143');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('168', 'Fukien', 'FK', '217');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('169', 'Kaohsiung', 'KA', '217');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('170', 'Taipei', 'TP', '217');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('171', 'Taiwan', 'TWN', '217');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('172', 'Alabama', 'AL', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('173', 'Alaska', 'AK', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('174', 'Arizona', 'AZ', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('175', 'Arkansas', 'AR', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('176', 'California', 'CA', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('177', 'Colorado', 'CO', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('178', 'Connecticut', 'CN', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('179', 'Delaware', 'DE', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('180', 'Florida', 'FL', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('181', 'Georgia', 'GA', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('182', 'Hawaii', 'HW', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('183', 'Idaho', 'IH', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('184', 'Illinois', 'IL', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('185', 'Indiana', 'IN', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('186', 'Iowa', 'IA', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('187', 'Kansas', 'KN', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('188', 'Kentucky', 'KT', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('189', 'Louisiana', 'LO', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('190', 'Maine', 'ME', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('191', 'Maryland', 'MA', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('192', 'Massachusetts', 'MS', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('193', 'Michigan', 'MI', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('194', 'Minnesota', 'MN', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('195', 'Mississippi', 'MS', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('196', 'Missouri', 'MO', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('197', 'Montana', 'MT', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('198', 'Nebraska', 'NE', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('199', 'Nevada', 'NV', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('200', 'New Hampshire', 'NH', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('201', 'New Jersey', 'NJ', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('202', 'New Mexico', 'NM', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('203', 'New York', 'NY', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('204', 'North Carolina', 'NC', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('205', 'North Dakota', 'ND', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('206', 'Ohio', 'OH', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('207', 'Oklahoma', 'OK', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('208', 'Oregon', 'OR', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('209', 'Pennsylvania', 'PA', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('210', 'Rhode Island', 'RI', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('211', 'South Carolina', 'SC', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('212', 'South Dakota', 'SD', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('213', 'Tennessee', 'TN', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('214', 'Texas', 'TX', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('215', 'Utah', 'UT', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('216', 'Vermont', 'VM', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('217', 'Virginia', 'VA', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('218', 'Washington', 'WA', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('219', 'Washington, D.C.', 'DC', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('220', 'West Virginia', 'WV', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('221', 'Wisconsin', 'WI', '235');
INSERT INTO `supply_chain`.`geo_state` (`STATE_ID`, `STATE_NAME`, `STATE_CODE`, `STATE_COUNTRY`) VALUES ('222', 'Wyoming', 'WY', '235');


/** INSERT DEFAULT STORAGE **/
INSERT INTO `supply_chain`.`sys_storage` (`STORAGE_ID`,`STORAGE_CODE`,`STORAGE_NAME`,`STORAGE_STREET_ADDRESS`,`STORAGE_CITY`,`STORAGE_STATE`) VALUES(1,'101','NG Laredo','14414 Import Rd.','Laredo','214');