CREATE TABLE `supply_chain`.`cat_company_role` (
  `COMPANY_ROLE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `COMPANY_ROLE_NAME` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`COMPANY_ROLE_ID`)  COMMENT '',
  UNIQUE INDEX `COMPANY_ROLE_NAME_IDX` (`COMPANY_ROLE_NAME` ASC) COMMENT ''
  );

CREATE TABLE `supply_chain`.`cat_company` (
  `COMPANY_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `COMPANY_NAME` VARCHAR(150) NOT NULL COMMENT '',
  `COMPANY_ALIAS` VARCHAR(150) NULL COMMENT '',
  `COMPANY_STREET_ADDRESS` VARCHAR(100) NULL COMMENT '',
  `COMPANY_ADDITIONAL_ADDRESS` VARCHAR(100) NULL COMMENT '',
  `COMPANY_CITY` VARCHAR(50) NULL COMMENT '',
  `COMPANY_STATE` INT NULL COMMENT '',
  `COMPANY_ZIP` VARCHAR(10) NULL COMMENT '',
  `COMPANY_PHONE` VARCHAR(15) NULL COMMENT 'ONLY NUMBERS, FORMAT TO BE APPLIED IN DISPLAY LAYER',
  `COMPANY_PHONE_SEC` VARCHAR(15) NULL COMMENT 'ONLY NUMBERS, FORMAT TO BE APPLIED IN DISPLAY LAYER',
  `COMPANY_FAX` VARCHAR(15) NULL COMMENT 'ONLY NUMBERS, FORMAT TO BE APPLIED IN DISPLAY LAYER',
  `COMPANY_EMAIL` VARCHAR(80) NULL COMMENT '',
  `COMPANY_WEB` VARCHAR(80) NULL COMMENT '',
  PRIMARY KEY (`COMPANY_ID`)  COMMENT '',
  UNIQUE INDEX `COMPANY_NAME_IDX` (`COMPANY_NAME` ASC)  COMMENT '',
  INDEX `FK_STATE_idx` (`COMPANY_STATE` ASC)  COMMENT '',
  FOREIGN KEY (`COMPANY_STATE`) REFERENCES `supply_chain`.`geo_state` (`STATE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
  );

CREATE TABLE `supply_chain`.`cross_company_role` (
  `CROSS_COMPANY_ROLE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `COMPANY_ID` INT NOT NULL COMMENT '',
  `COMPANY_ROLE_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`CROSS_COMPANY_ROLE_ID`)  COMMENT '',
  UNIQUE INDEX `COMPANY_ROLE_IDX` (`COMPANY_ID` ASC, `COMPANY_ROLE_ID` ASC)  COMMENT '',
  INDEX `FK_COMPANY_ID_idx` (`COMPANY_ID` ASC)  COMMENT '',
  INDEX `FK_COMPANY_ROLE_ID_idx` (`COMPANY_ROLE_ID` ASC)  COMMENT '',
  FOREIGN KEY (`COMPANY_ID`) REFERENCES `supply_chain`.`cat_company` (`COMPANY_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (`COMPANY_ROLE_ID`) REFERENCES `supply_chain`.`cat_company_role` (`COMPANY_ROLE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('purchaser');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('seller');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('sender');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('receiver');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('exporter');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('importer');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('freighter');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('insurer');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('bank');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('client');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('payer');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('charger');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('gov-agency');
INSERT INTO `supply_chain`.`cat_company_role` (`COMPANY_ROLE_NAME`) VALUES ('customs-broker');
